resource_types:
  - name: local
    type: docker-image
    source:
      repository: concourse/docker-image-resource
      tag: latest
      privileged: true
    params:
      check_local_filesystem: true


resources:
  - name: every-five-minutes
    type: time
    source:
      interval: 5m

  - name: local-files
    type: local
    source:
      path: /home/user619/Repo/kek/

jobs:
  - name: hello-world-job
    plan:
      - get: every-five-minutes
        trigger: true
      - get: local-files 
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11"
          inputs:
            - name: local-files
          outputs:
            - name: the-artifact
          run:
            path: sh
            args:
              - -cx
              - |
                ls -l .
                echo "hello from another step!" > the-artifact/message
      # Add a second task that reads the contents of the-artifact/message
      - task: read-the-artifact
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          # To receive "the-artifact", specify it as an input
          inputs:
            - name: the-artifact
          run:
            path: sh
            args:
              - -cx
              - |
                ls -l .
                cat the-artifact/message
