resources:
  - name: my-git-repo
    type: git
    source:
      uri: https://github.com/chyvak357/concourse_test.git
      branch: main
      # private_key: ((git-private-key))

  - name: every-five-minutes
    type: time
    source:
      interval: 5m

jobs:
  - name: hello-world-job
    plan:
      - get: every-five-minutes
        trigger: true
      - get: repo
        resource: my-git-repo
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11"
          inputs:
            - name: repo
          # outputs:
          #   - name: the-artifact
          run:
            path: sh
            args:
              - -cx
              - |
                ls -l .
                ls -l ./repo
                ./repo/task.sh
          # run:
            # path: ./repo/task.sh
            
      # Add a second task that reads the contents of the-artifact/message
      # - task: read-the-artifact
      #   config:
      #     platform: linux
      #     image_resource:
      #       type: registry-image
      #       source:
      #         repository: busybox
      #     # To receive "the-artifact", specify it as an input
      #     inputs:
      #       - name: the-artifact
      #     run:
      #       path: sh
      #       args:
      #         - -cx
      #         - |
      #           ls -l .
      #           cat the-artifact/message
