resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
      tag: latest

resources:
  - name: send-an-email
    type: email
    source:
      smtp:
        host: smtp.ethereal.email
        port: "587"
        username: keith88@ethereal.email
        password: 4XWW4P1y1KjFW31B6c
      from: chyvak357@yandex.ru
      to: ["keith88@ethereal.email"]

  # - name: send-an-email
  #   type: email
  #   source:
  #     smtp:
  #       host: smtp.yandex.com
  #       port: "465"
  #       username: test_pass
  #       password: slotlbkvnososzqc
  #     from: chyvak357@yandex.ru
  #     to: ["chyvak357@gmail.com"]

  - name: my-git-repo
    type: git
    source:
      uri: https://github.com/chyvak357/concourse_test.git
      branch: main

  - name: every-five-minutes
    type: time
    source:
      interval: 5m

jobs:
  - name: send-email
    plan:
      - put: send-an-email
        params:
          subject_text: "Email resource: build"
          body_text: |
            Cheers!

  - name: hello-world-job
    plan:
      - get: every-five-minutes
        trigger: true
      - get: repo
        resource: my-git-repo
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11"
          inputs:
            - name: repo
          outputs:
            - name: email-out
          run:
            # path: ./repo/task.sh
            path: sh
            args:
              - -cx
              - |
                ls -l .
                ls -l ./repo
                ./repo/task.sh

      - put: send-an-email
        params:
          subject: email-out/generated-subject
          body: email-out/generated-body

      # Add a second task that reads the contents of the-artifact/message
      # - task: read-the-artifact
      #   config:
      #     platform: linux
      #     image_resource:
      #       type: registry-image
      #       source:
      #         repository: busybox
      #     # To receive "the-artifact", specify it as an input
      #     inputs:
      #       - name: the-artifact
      #     run:
      #       path: sh
      #       args:
      #         - -cx
      #         - |
      #           ls -l .
      #           cat the-artifact/message
